name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  integration:
    uses: ./Ch03/03_04_ci_cd_for_container_images/python-ci-workflow.yml
    permissions:
      contents: read
      checks: write
      
  build:
    needs: [integration]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
